### ISSUE TITLE
[Coverage] : DENTAL -> No alternative text found

### ISSUE THREAD

**Issue by satkanhub** [veshu/accessibility-bughunt-bluesource#100]
**Describe the bug**
No alternate text found for the images with link

**To Reproduce**
1. Go to http://localhost:4200/coverage
2. Click on DENTAL
3. Click on WAVE this page using the chrome extension
4. Observe the error

**Expected behavior**
Combine the redundant links into one link and remove any redundant text or alternative text. Redundant links to be removed.

**Device**: Desktop
**Operating System**: Windows 10 Home
**Browser(with version)**: Chrome Version Version 78.0.3904.87 (Official Build) (64-bit)

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.4.4 Link Purpose (In Context)
**Tools used**: WAVE

**Attachments**
![image](https://user-images.githubusercontent.com/51492004/67995975-84128b80-fc4d-11e9-93ea-722c598d7610.png)

**Comment by drasticdpk** [comment]
https://github.com/veshu/accessibility-bughunt-bluesource/issues/90
