### ISSUE TITLE
[Claims] Claims page all heading read out multipe time by narrator

### ISSUE THREAD

**Issue by Krishna1507** [veshu/accessibility-bughunt-bluesource#104]
**Describe the bug**
The narrator read out multiple times account notification tab 

**Step to reproduce**
1) Go to app localhost:4200/claims
2) Click All claims, EOF,  Claims forms tab and listen
3) The narrator read out twice

**Expected behavior**
Screen reader should be read out only once

**Device**: Laptop
**Operating System**: Windows 10
**Browser**: Edge 44.18362.387.0

**WCAG Category**: 1.  Perceivable
**WCAG Level**: A
**WCAG Success Criterion**: 1.3.2 Meaningful sequence
**Tools used**: Narrator

**Attachments**
https://drive.google.com/open?id=1D08awNoC-XINX522xcELgrFC-OjQQ4_I

**Comment by drasticdpk** [comment]
https://github.com/veshu/accessibility-bughunt-bluesource/issues/101
