### ISSUE TITLE
Navigation Issue on Safari under Home->Pay Your Premium ->Go To Billing

### ISSUE THREAD

**Issue by sraarum87** [veshu/accessibility-bughunt-bluesource#15]
**Describe the bug**
Navigation doesn't work fine on Safari Browser. Pressing tab on Go To Billing window navigates from Close Window to Previous Web page instead of moving to Continue Button. This works fine on Chrome Browser.

**To Reproduce**
1. Go to Home->Pay Your Premium ->Go To Billing
2. Click on Continue Button and Press tab key
3. This navigates to Main page instead of going to Continue tab.
4. See error screenshot

**Expected behavior**
Tab key should navigate to Continue button, it works fine on Chrome. Initial step in video explains it works fine on Chrome and not on Safari.
**Device**: Labtop
**Operating System**: MacOS 10.14.6
**Browser(with version)**: Safari Version 13.0.3 (14608.3.10.10.1)

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Tools used**: VoiceOver for MacOS

**Attachments**
https://drive.google.com/drive/folders/1nvI4rXObmA35CRxJR82cqwPdHO1yGrJl

**Comment by drasticdpk** [comment]
This is Safari browser features : 
you can set it from safari >> preference > Advanced 
![image](https://user-images.githubusercontent.com/25297859/68045129-e9738480-fd00-11e9-992a-44221423db74.png)
