### ISSUE TITLE
Invalid Date format error

### ISSUE THREAD

**Issue by sraarum87** [veshu/accessibility-bughunt-bluesource#29]
**Describe the bug**
Clicking on View button without changing the date value throws an error as invalid Date format.

**To Reproduce**
1. Go to Home Page ->Coverage->Benefit Period ->Custom Date ->Date 10/31/2019
2. Click on 'View"
3. Observe
4. This throws an error when clicked on View without editing Date value. Error goes off when same date is entered manually. This happens on Chrome and Firefox browsers.

**Expected behavior**
No error should be reported as the date is still valid.

Device: Laptop
Operating System: MacOS 10.14.6
Browser(with version): Safari Version 13.0.3 (14608.3.10.10.1)
Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Tools used**: VoiceOver for MacOS

**Attachments**
https://drive.google.com/drive/folders/1VYzvSpHV1nGaoPosaDLVHo9nZ9_Kf7P5

**Comment by drasticdpk** [comment]
It is functional bug rather than accessibility.
