### ISSUE TITLE
Invalid email id gets accepted MyPlans->ID Card->View ID CARD->EMail

### ISSUE THREAD

**Issue by sraarum87** [veshu/accessibility-bughunt-bluesource#34]
**Describe the bug**
Invalid email id gets accepted MyPlans->ID Card->View ID CARD->EMail

**To Reproduce**
1. Go to Home Page, select MyPlans->ID Card->View ID CARD->EMail
2. Type Special Characters ++--@Test.com
3. Click on Send, this doesnt throw any error.
4. Observe for successful message.

**Expected behavior**
Should throw an error when invalid email id entered.

Device: Laptop
Operating System: MacOS 10.14.6
Browser(with version): Safari Version 13.0.3 (14608.3.10.10.1)
Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Tools used**: VoiceOver for MacOS

**Attachments**
https://drive.google.com/drive/folders/14N2FgplDZKW4CADTc7A7On8cwJQc5K1A

**Comment by drasticdpk** [comment]
It is functional issue.
