### ISSUE TITLE
Unable to Save the Note, Options Add Note and Edit Note doesnt work after clicking on Save

### ISSUE THREAD

**Issue by sraarum87** [veshu/accessibility-bughunt-bluesource#37]
**Describe the bug**
Unable to Save the Note, Options Add Note and Edit Note doesnt work after clicking on Save

**To Reproduce**
1. Go to Claims
2. Click on 'Edit Note or Add Note under My Notes.
3. Click on Save and Observe.
4. See error, it shows Saving.

**Expected behavior**
Notes should get saved.

Device: Laptop
Operating System: MacOS 10.14.6
Browser(with version): Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Tools used**: VoiceOver for MacOS

**Attachments**
https://drive.google.com/drive/folders/1Won5WjSGi5VJD8PxOl5cZ9_gKhFPyVI-

**Comment by drasticdpk** [comment]
This is functional issue.
