### ISSUE TITLE
Application is focusing on whole field of the link.

### ISSUE THREAD

**Issue by bhattashubham** [veshu/accessibility-bughunt-bluesource#4]
**To Reproduce**
1. Go to homepage 
2. Click on "Coverage".
3. Click on "Benefit period" dropdown and select "Custom Date".
4. Click on "View" without making any changes.
5. Hit "Tab" once and observe the marked area.

**Expected behavior**
Application should only focus around the link that appeared.

**Device**: Laptop Dell

**Operating System**: Windows 10

**Browser(with version)**: Chrome 78.0.3904.70

**WCAG Category**: 2. Operable

**WCAG Level**: 

**WCAG Success Criterion**: 

**Tools used**: JAWS

**Video**:
https://drive.google.com/open?id=1B3GUIfpWlZB_2lTnphUpDHyzzn_9OwWN

**Comment by drasticdpk** [comment]
This is GUI bug and WCAG Level is missing.
