### ISSUE TITLE
[Profile][NVDA] Not able read ACCOUNT tab, when user navigate back to account tab from Notifications tab.

### ISSUE THREAD

**Issue by bhattashubham** [veshu/accessibility-bughunt-bluesource#44]
## Steps to reproduce the behavior
1. Go to Wellmark App.
2. Press Tab Key and reach Profile link.
3. Press Enter Key.
4. Press Tab key, focus on NOTIFICATION.
5. Press Right arrow and focus Account Tab.
6. Listen the reading.

## Actual behavior:
When user navigate back to account tab from Notifications tab, app is reading as "Out of tab tab selected expanded."

## Expected behavior:
When user navigate back to account tab from Notifications tab, app should read as "Account tab selected expanded."

Device: Laptop

Operation System: Windows 10

Browser: Microsoft Edge 44.17763.771.0

WCAG Category: 3. Understandable

WCAG Level A

WCAG Success Criteria 3.3.2 Labels or Instructions

Tools used: NVDA

Video:
https://drive.google.com/open?id=1PFs2-9TYiBzmR7G4iM9FscaF43BeR-tH

**Comment by drasticdpk** [comment]
5. Press Right arrow and focus Account Tab.
>> You should use up arrow here.
