### ISSUE TITLE
Contents overlapping when user sets date range to 90 days.

### ISSUE THREAD

**Issue by bhattashubham** [veshu/accessibility-bughunt-bluesource#5]
**To Reproduce**
1. Go to homepage 
2. Click on "Claims".
3. Click on "Claims Date Range" dropdown and select "Last 90 Days".
4. Observe the results displayed.

**Expected behavior**
Displayed results should be shown and written clearly.

**Device**: Laptop Dell

**Operating System**: Windows 10

**Browser(with version)**: Chrome 78.0.3904.70

**WCAG Category**: 2. Operable

**WCAG Level**: AA

**WCAG Success Criterion**:  1.4.12 Text Spacing

**Tools used**: JAWS

**Video**:
https://drive.google.com/open?id=1DeYNwUCO8wj_22nkhGR3LFEIANGt45d3

**Comment by drasticdpk** [comment]
1. WCAG Category and  WCAG Success Criterion  miss-match.
2. This not caused by JAWS
