### ISSUE TITLE
[Home] - User is unable to navigate through the home page sequentially

### ISSUE THREAD

**Issue by CreeyaSean** [veshu/accessibility-bughunt-bluesource#56]
**To Reproduce**:
1. Go to the home page.
2. Hit the tab button to navigate through the page and observe.

**Expected behavior**
Users should be able to navigate through the page successfully.

**Device**: Laptop MacBook Air

**Operating System**: macOS Mojave (10.4.6)

**Browser(with version)**: Safari 13.0.3

**WCAG Category**: 2. Operable

**WCAG Level**: A

**WCAG Success Criterion**: 1.3.2 Meaningful Sequence 

**Tools used**: Voiceover

**Video**:
https://drive.google.com/open?id=1B0tHkwbY3BjiEz5o5PWt1iosjcO_tQI6

**Comment by drasticdpk** [comment]
https://github.com/veshu/accessibility-bughunt-bluesource/issues/15
