### ISSUE TITLE
[Claim] - Claim number is not being notified by the application.

### ISSUE THREAD

**Issue by CreeyaSean** [veshu/accessibility-bughunt-bluesource#60]
**Steps To Reproduce**:
1. Go to the home page.
2. Click on "Claims" and click on "View" under "DETAILS".
3. Press "Option" + "tab" and hit "Control"+"Option"+"Space" and observe.

**Expected behavior**
The claim number and focused link should be mentioned by the application.

**Device**: Laptop MacBook Air

**Operating System**: macOS Mojave (10.4.6)

**Browser(with version)**: Safari 13.0.3

**WCAG Category**: 2. Operable

**WCAG Level**: A

**WCAG Success Criterion**: 3.3.2 Labels or Instructions

**Tools used**: Voiceover

**Video**:
https://drive.google.com/open?id=1NA6QQEFWOGFBl7E9M-IIIW8WTLaL9pXg

**Comment by drasticdpk** [comment]
https://github.com/veshu/accessibility-bughunt-bluesource/issues/59
