### ISSUE TITLE
[Home] - Non-clickable content is being read out as Clickable content.

### ISSUE THREAD

**Issue by CreeyaSean** [veshu/accessibility-bughunt-bluesource#71]
**Steps To Reproduce**:
1. Go to the home page.
2. Click on "Home".
1. Press "Option" +  "Shift" + "Tab" keys to navigate until the user reaches "Skip to main content."
1. Press "Control" + "Option" + "Space" keys and listen carefully.

**Expected behavior**:
The application should properly read out the contents, i.e. non-clickable heading should not be read as clickable content.

**Device**: Laptop MacBook Air

**Operating System**: macOS Mojave (10.4.6)

**Browser(with version)**: Safari 13.0.3

**WCAG Category**: 3. Understandable

**WCAG Level**: A

**WCAG Success Criterion**: 3.3.2 Labels or Instructions

**Tools used**: Voiceover

**Video**:
https://drive.google.com/open?id=1qdgzinbJKFZjsbTfeUE9xWAKo1PJv01D

**Comment by drasticdpk** [comment]
Working fine on my machine.
