### ISSUE TITLE
Web - printing and saving file as PDF format is not correct. Overlapping text with icon and exceeding Page size out of the box. 

### ISSUE THREAD

**Issue by akultalwar89** [veshu/accessibility-bughunt-bluesource#83]
Go to Web app
Click on Claims tab
View any claim or the first one 
Click on Print button
UI should be in proper format with size of table and Claim text heading should be clear. 

Actual Result - UI is not proper while printing a page or saving it as pdf file

Expected Result - UI should be proper, text is going out of place and Claims and > is clubbing together.

Device: Laptop MacBook Air

Operating System: macOS Catalina (10.15)

Browser(with version): Chrome - Version 78.0.3904.70

Tools used: Voiceover

One drive Link - 
https://drive.google.com/open?id=1JDei7zf6WKkggjOqsjeXIlPBC_UOVE36

**Comment by akultalwar89** [comment]
Hi @drasticdpk  - any reasons for rejection?

**Comment by drasticdpk** [comment]
Hi @akultalwar89 , 
You have missed below attribute, it is web accessibility testing so without it we could not approved it. 
WCAG Category: 
WCAG Level: 
WCAG Success Criterion:

**Comment by akultalwar89** [comment]
Thank you @drasticdpk  Deepak  , Any possibility that i can update it now?

**Comment by akultalwar89** [comment]
I am asking this because its a genuine issue and should not be missed.
