### ISSUE TITLE
[Coverage] : PHARMACY -> No alternative text found

### ISSUE THREAD

**Issue by satkanhub** [veshu/accessibility-bughunt-bluesource#99]
**Describe the bug**
No alternate text found for the images with link

**To Reproduce**
1. Go to http://localhost:4200/coverage
2. Click on PHARMACY
3. Click on WAVE this page using the chrome extension
4. Observe the error

**Expected behavior**
Images that are the only thing within a link must have descriptive alternative text.

**Device**: Desktop
**Operating System**: Windows 10 Home
**Browser(with version)**: Chrome Version Version 78.0.3904.87 (Official Build) (64-bit)

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.4.4 Link Purpose (In Context)
**Tools used**: WAVE

**Attachments**
![image](https://user-images.githubusercontent.com/51492004/67995772-89230b00-fc4c-11e9-96ad-9081b287f218.png)

**Comment by drasticdpk** [comment]
https://github.com/veshu/accessibility-bughunt-bluesource/issues/90
